### ISSUE TITLE
Unnecessary "hasher.changed" events fires

### ISSUE THREAD

**Issue by th0r** [millermedeiros/Hasher#39] opened 2012-05-05 13:19 UTC
I've found an issue while trying to do some kind of redirects using your lib.
Test code is this:

``` javascript
function log(msg) {
    var elem = document.createElement('div');
    elem.innerHTML = msg;
    document.body.appendChild(elem);
}

var hashChangeHandler = function(newHash) {
    if (newHash === '') {
        log('changing hash to "one"');
        hasher.replaceHash('one');
    } else if (newHash === 'one') {
        log('changing hash to "two"');
        hasher.replaceHash('two');
    } else {
        log('hash changed to "two"');
    }
};

hasher.initialized.add(function(hash) {
    log('inited event fired with hash "' + hash + '"');
    hashChangeHandler(hash);
});
hasher.changed.add(function(hash) {
    log('changed event fired with hash "' + hash + '"');
    hashChangeHandler(hash);
});

window.onload = function() {
    hasher.init();
};
```

Here i'm doing some redirects in "hasher.changed" event using "hasher.replaceHash" method.
So if we'll go to the page containing this script using empty hash, the output will be this:

```
inited event fired with hash ""
changing hash to "one"
changed event fired with hash "one"
changing hash to "two"
changed event fired with hash "two"
hash changed to "two"
changed event fired with hash "one"
changing hash to "two"
changed event fired with hash "two"
hash changed to "two"
```

So you can see there are unnecessary change events fired in this case.
This is because of this line in "hasher.setHash" and "hasher.replaceHash" methods in your code:

``` javascript
_registerChange(path); //avoid breaking the application if for some reason `location.hash` don't change
```

As for me, there is no need to call "_registerChange" in these functions because it will be called by "hashchange" event listener.
I think there is no circumstances when the hash won't change.

You can see it at http://grunin-ya.ru/sandbox/hasher-issue.html

**Comment by millermedeiros** [comment] 2012-05-05 16:42
This is the expected output. The only difference between `replaceHash()` and `setHash()` is that `replaceHash()` doesn't keep the previous hash in the browser history. Both should dispatch the `changed` event since both changes the `location.hash` value. To update the hash value without triggering a `changed` event you should disable the `changed` signal and re-enable it afterwards like the [example on the README file](https://github.com/millermedeiros/Hasher/blob/master/README.md#setting-hash-value-without-dispatching-changed-signal).

I [just updated the README](https://github.com/millermedeiros/Hasher/commit/8c4e630f0ea2b2f9b33f019354eecbfcc847ff7b) file with info about this behavior.

Closing it since it's working as designed. Cheers.

**Comment by th0r** [comment] 2012-05-06 10:34
I know that `replaceHash()` and `setHash()` are both triggering `change` event. What I'm triying to say is that they triggers it two times instead of one. 
This is the code in `replaceHash()`:

``` javascript
setHash : function(path){
            path = _makePath.apply(null, arguments);
            if(path !== _hash){
                _registerChange(path); //avoid breaking the application if for some reason `location.hash` don't change
                location.hash = '#'+ encodeURI(path); //used encodeURI instead of encodeURIComponent to preserve '?', '/', '#'. Fixes Safari bug [issue #8]
            }
        },
```

In this code the line `_registerChange(path);` dispatches `change` event immediately, and line `location.hash = '#'+ encodeURI(path);` changes the hash, that triggers the browser `hashchange` event, which is calling `_registerChange` again.
I've shown it to you in my example above - there are 2 `change` events with hashes `#one` and `#two` were dispatched instead of one.
I think `setHash()` and `replaceHash()` methods shouldn't dispatch `change` event immediately - it will be fired in `onhashchange` event, that will be triggered right after hash change.

**Comment by millermedeiros** [comment] 2012-05-06 21:52
Hasher is working as expected. Try this:

``` js
hasher.changed.add(console.log, console);
hasher.setHash('foo');
hasher.setHash('foo');
hasher.setHash('foo');
```

You should see a single log. If you look at the `_registerChange` code it checks if the newHash is different than the current hash before dispatching the `changed` event. Doing like this we avoid errors in case the onhashchange doesn't  fire (older versions of firefox had a bug after hundreds of changes which I couldn't isolate).

**Comment by th0r** [comment] 2012-05-07 00:17
This bug appears if you make **multiple redirects**, using `setHash()` or `replaceHash()` **in `hasher.changed` event handler**. It's shown in my [example](http://grunin-ya.ru/sandbox/hasher-issue.html).
And I can try to explain it to you. Here's what happens:
1) Hasher inits and trigger `changed` event with `newHash = ""`
2) My `change` event handler redirects from empty hash to `one`, using `replaceHash("one")` method.
3) `replaceHash()` method calls `_registerChange()` function, that changes `_hash` variable to "one" and fires another `changed` event with hash "one". **It's not going to the next line of code:**

``` javascript
location.replace('#'+ encodeURI(path));
```

**It's very important! It's not changing browser hash to "one"! It'll do it later and this is where the bug is!** So, continue...
4) My change event handler executes again and calls `replaceHash("two")`. **It puts "two" in `_hash` variable**, and fires `changed` event with this value. This time my `changed` event handler makes no redirects and finishes.
Then `location.replace("#two")` is called **and immediately after this `location.replace("#one")` is made!**
It generates browser `hashchange` event **with hash "#one"!**. Your `hashchange` handler compares this "one" value with value in `_hash` variable (**it's "two"!**) and **dispatches `changed` event with hash "one"** and the chain begins again...

You wrote beautiful libs for client-side routing (this and crossroads.js), but this issue stops me from using it in my big project.
I hope you'll find some time to deal with this issue. Thank you!

**Comment by millermedeiros** [comment] 2012-05-07 03:11
@th0r ohh, now I get what you are talking. The problem is the 2 consecutive redirects.. re-opening it and will add a test case for it.

**Comment by millermedeiros** [comment] 2012-05-13 01:00
I just created a test on the `iss39` branch and it doesn't seem that easy to fix since removing the `registerChange` from `setHash`/`replaceHash` makes the other tests fail. If we wait the browse hashchange event to dispatch to dispatch the `hasher.changed` signal you will get to weird scenarios like:

``` js
hasher.setHash('foo');
hasher.getHash(); // "lorem/ipsum"
```

Since the browser takes a while to update the value (it's async). It also won't dispatch all the changes:

``` js
// if we remove the `_registerChange()` from `setHash()`
// this might cause a single change event (instead of 3) depending on the browser
hasher.setHash('one');
hasher.setHash('two');
hasher.setHash('three');
```

Not sure when I will have time to fix it, feel free to ask for a pull request in case you fix it without breaking the other tests.

PS: the unit test only works properly if you open a new window/tab and do a "fresh" run, chrome and firefox seems to have a browser history limit (maybe a limit for consecutive updates) and since the test does hundreds of changes you get to the limit very easily making the test fail after a couple runs.

**Closed as completed** 2012-10-31 15:29 UTC
Labels: defect
